version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: acme-frontend
    ports:
      - "80:3000"
    environment:
      - DB_HOST=10.0.133.48
      - DB_USER=acme_user
      - DB_PASS=acme1234
      - DB_NAME=acme_erp
    networks:
      - acme-net
    restart: always
networks:
  acme-net:
    driver: bridge
